;; autogenerated by lispmake revision 11
;; DO NOT EDIT
(compile-file "package.lisp" :output-file "package.lisp.fasl" :verbose t)
(compile-file "lispmake.lisp" :output-file "lispmake.lisp.fasl" :verbose t)
(compile-file "lisp-specific.lisp" :output-file "lisp-specific.lisp.fasl" :verbose t)
(compile-file "plugin.lisp" :output-file "plugin.lisp.fasl" :verbose t)
(load #P"package.lisp.fasl")
(load #P"lispmake.lisp.fasl")
(load #P"lisp-specific.lisp.fasl")
(load #P"plugin.lisp")
#+sbcl (sb-ext:save-lisp-and-die "lispmake" :executable t :toplevel #'LISPMAKE:MAIN)
#+ccl (ccl:save-application lispmake :toplevel-function #'LISPMAKE:MAIN :prepend-kernel t)
#+clisp (ext:saveinitmem lispmake :init-function #'LISPMAKE:MAIN :executable t :norc t)
