(in-package :lispmake)

(defvar *debugging* nil)
(defvar *lispmake-version* 14)
(defvar *sources* nil)
(defvar *outfile* nil)
(defvar *lm-package* nil)
(defvar *toplevel* nil)
(defvar *quickloads* nil)
(defvar *generate* nil)
(defvar *compile-files* nil)
(defvar *lisp-executable* nil)
(defvar *do-build* nil)
(defvar *lisp-target* 'default)
(defvar *plugins* nil)
(defvar *pregen-hooks* nil)
(defvar *postgen-hooks* nil)
(defvar *lmakefile* "LMakefile")
(defvar *target* nil)

(defun output-fname ()
  (if (eq *target* nil)
      "run-build.lisp"
      (format nil "run-~A.lisp" *target*)))
